artifacts_root: artifacts


data_ingestion:
  DATASET_NAME: Revankumar/News_room


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/newsroom_dataset
  tokenizer_name: t5-small



model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/newsroom_dataset
  model_ckpt: t5-small




model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/newsroom_dataset
  model_path: artifacts/model_trainer/t5-small-newsroom-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv


